25localeat/localeat-f

src/pages/cart/CartGeneral.jsx

✨CartUI#2[UI구현] (#2)

---

src/App.js
src/pages/cart/CartGeneral.css
src/pages/cart/CartGroupBuy.jsx
src/pages/cart/CartSubscribe.jsx

장바구니/일반배송 디자인 수정
장바구니/구독 디자인 구현
장바구니/공동구매 디자인 구현

✨Feat/Style/CartUI#2 [UI 수정 및 구현]

---

src/App.js
src/components/Navbar/Navbar.css
src/components/Navbar/Navbar.jsx
src/pages/MypageBuyer/BuyerMemberEdit.css
src/pages/MypageBuyer/BuyerMemberEdit.jsx
src/pages/MypageBuyer/BuyerOrderHistory.css
src/pages/MypageBuyer/BuyerOrderHistory.jsx
src/pages/MypageBuyer/BuyerReviewManage.css
src/pages/MypageBuyer/BuyerReviewManage.jsx
src/pages/MypageBuyer/GroupBuyStatus.css
src/pages/MypageBuyer/GroupBuyStatus.jsx
src/pages/MypageBuyer/SubscribeManage.css
src/pages/MypageBuyer/SubscribeManage.jsx
src/pages/MypageBuyer/WishlistManage.css
src/pages/MypageBuyer/WishlistManage.jsx

✨Design: Add 판매자마이페이지 UI

---

src/components/Navbar/Navbar.css
src/pages/home/Home.jsx
src/pages/search/Search.css
src/pages/search/Search.jsx

💄Style/SearchUI#5 [ 검색 화면 css, 양옆 간격 수정, 디테일 수정 ]

---

package-lock.json
package.json
src/App.js
src/components/Navbar/Navbar.jsx
src/pages/Login/Login.css
src/pages/Login/Login.jsx
src/pages/SignUp/Agreement.css
src/pages/SignUp/Agreement.jsx
src/pages/SignUp/Complete.css
src/pages/SignUp/Complete.jsx
src/pages/SignUp/FormSeller.css
src/pages/SignUp/FormSeller.jsx
src/pages/SignUp/SelectType.css
src/pages/SignUp/SelectType.jsx

회원가입 관련된 페이지 UI 생성 related to #1

💄Style/Login#1 [회원가입 UI 구현]

---

src/pages/SignUp/FormConsumer.jsx

구매자 회원 정보 입력 페이지 수정 related to #26

✨Update 구매자 회원가입 페이지 연결

---

package-lock.json
package.json
src/pages/SignUp/FormConsumer.jsx

구매자 회원가입 및 로그인 완성 related to #26

✨Update 구매자 회원가입 및 로그인 완성

---

src/components/Ui/Popup/Popup.jsx
src/pages/SignUp/FormSeller.jsx

판매자 회원가입 창 팝업 및 api 연결 수정 related to #26

✨Update 판매자 회원가입창 수정

---

src/components/Ui/Popup/Popup.jsx
src/pages/Login/Login.jsx

✨Update 로그인창 구현 완료

---

src/components/Ui/Popup/Popup.jsx

✨Add 회원가입 팝업

---

src/pages/SignUp/FormConsumer.jsx
src/pages/SignUp/FormSeller.jsx

회원가입 아이디 중복 검사 오류 수정 related to #26

✨Update 회원가입 중복 확인 검사 수정

---

src/pages/GroupBuy/JoinGroupBuy.css
src/pages/GroupBuy/JoinGroupBuy.jsx

공동구매 참여하기 페이지 UI 수정 related to #20

💄Fix: 공동구매 참여하기 페이지 UI 수정

---

src/pages/GroupBuy/CreateGroupBuy.css
src/pages/GroupBuy/CreateGroupBuy.jsx
src/pages/GroupBuy/JoinGroupBuy.jsx
src/pages/GroupBuy/ViewGroupBuy.css
src/pages/GroupBuy/ViewGroupBuy.jsx

공동구매 만들기 페이지 css 오류 수정 related to #38

💄공동구매 만들기 페이지 css 오류 수정

---

src/pages/MypageSeller/ProductList.jsx
src/pages/MypageSeller/ProductRegister.jsx

- ProductRegister.jsx: 수정 시 이미지 미업로드 허용
- productName 필드 매핑 오류 수정 (name → productName)
- 등록/수정 시 PUT/POST 분기 로직 안정화
- ProductList.jsx: 수정 진입 시 editData 구조 반영

feat: 상품 수정 기능 개선 및 이미지 업로드 예외 처리

---

src/pages/MypageSeller/ProductRegister.jsx

백엔드에서 seller id 대신 객체를 받아오게 수정함에 따라 프론트에서 product 객체 저장 시 seller id 받아오게 수정함.

Style/product detail UI

---

src/pages/GroupBuy/JoinGroupBuy.css
src/pages/GroupBuy/JoinGroupBuy.jsx

공동구매 참여하기 페이지 UI 수정 related to #20

💄공동구매 참여하기 페이지 UI 수정

---

src/pages/GroupBuy/CreateGroupBuy.jsx

✨Add 공동구매 생성 API 연결

---

src/pages/GroupBuy/CreateGroupBuy.jsx

공동구매 생성 API 연결 완료 related to #38

✨Feat:공동구매 생성 API 연결

---

src/pages/GroupBuy/ViewGroupBuy.jsx
src/pages/Login/Login.jsx
src/pages/productDetail/ProductMainInfo.jsx

상품 상세 페이지에서 공동구매 조회 페이지로 렌더링 추가 related to #38

✨Feat: Add 공동구매 조회 페이지로 렌더링 추가

---

src/pages/cart/CartGroupBuy.jsx

#38 
공동구매 장바구니 api 연결
오류 있어서 이 페이지로 넘어가면 에러 뜨십니다...!

✨Feat: Update 공동구매 장바구니 api 연결

---

src/pages/cart/CartGroupBuy.jsx

#38 
공동구매 장바구니 불러오기 오류 수정 및 공동구매 상품명, 가격 정보 불러오기 완료했습니다!
실제 화면

✨Fix: Update 공동구매 장바구니 api 연결 수정 완료

---

src/pages/cart/CartGroupBuy.jsx

#38 
공동구매 주문 버튼 누를시, 공동구매 주문까지 생성되는 api 연결
주문 완료 버튼 누르면 구매자 마이페이지 주문내역으로 이동하고,
생성된 주문 아이템 출력

✨Feat: Update 공동구매 주문 생성 api 연결

---

src/pages/MypageBuyer/WishlistManage.css
src/pages/MypageBuyer/WishlistManage.jsx
src/pages/productDetail/ProductDetail.jsx

ex) #1
feat: 찜(Wish) 목록 마이페이지에서 조회 및 삭제 기능 구현
- 백엔드 연동으로 로그인한 사용자의 찜 목록 불러오기 구현 (GET /api/wish?userId=...)
- 체크박스 선택 후 찜 항목 삭제 기능 추가 (DELETE /api/wish)
- 상세 페이지에서 찜 버튼 상태(isWished) 반영되도록 개선
- 하트 토글 시 백엔드 toggle API 연동 (POST /api/wish/{productId}?userId=...)
- 상품 상세 페이지 진입 시 찜 여부 자동 반영

feat: 찜(Wish) 목록 마이페이지에서 조회 및 삭제 기능 구현

---

src/components/Navbar/Navbar.jsx
src/components/Tag/tags.js
src/pages/MypageBuyer/WishlistManage.jsx
src/pages/home/FloatingButton.jsx
src/pages/home/Home.jsx
src/pages/search/Search.jsx

ex) #1
공동구매 list, B급 상품 list 부분 프론트 수정했습니다.
tag 에 code를 추가했습니다.
상단 네비게이션 바에서 "공동구매" 클릭 시, 공동구매가 가능한 상품 list만 출력됩니다.
Home 화면에서 B급 상품 버튼 클릭 시, B급 상품인 것들만 출력됩니다.

Feat : 공동구매, B급 상품 list 나오게 수정

---

src/components/Navbar/Navbar.css
src/components/Navbar/NavbarSeller.jsx
src/pages/MypageSeller/MemberEdit.jsx
src/pages/MypageSeller/OrderManagement.jsx
src/pages/MypageSeller/ProductList.jsx
src/pages/MypageSeller/ProductRegister.jsx
src/pages/SignUp/FormSeller.jsx

feat: 판매자 헤더 추가

---

src/pages/MypageSeller/MemberEdit.jsx

feat: 판매자 회원정보 수정 완료

---

src/pages/MypageBuyer/BuyerMemberEdit.jsx

feat: 구매자 회원정보수정 수정

---

public/firebase-messaging-sw.js
src/App.js
src/components/FCMToken.js
src/firebaseConfig.js
src/index.js
src/messaging.js
src/pages/Login/Login.jsx
src/pages/fcmtest.jsx
src/utils/fcm.js

#70 
1. FCM 연결 설정
2. 로그인 한 사용자 FCM 토큰 가져오기
3. 기기 변경 혹은 최초 로그인 시, FCM 토큰 발급
FCM 테스트 하실 때,
localhost:3000/FcmTest 경로로 가시면 발급 받으신 FCM 토큰 확인 가능하십니다~!
웹 브라우저 로그창에 로그인 정보와 함께 FCM 토큰 찍힘

✨Feat: Add FCM 토큰 발급 과정 추가

---

package-lock.json
package.json
src/components/Navbar/Alarm.jsx
src/components/Navbar/AlarmDropdown.css
src/pages/Login/Login.jsx

#70 
알림 조회, 읽기, 삭제 API 연결 완료했습니다!
제가... 살짝 CSS를 손 봤어요....
알림창 실제 화면

✨Feat/fcm alarm#70

---

src/components/Ui/Popup/Popup.jsx
src/components/api/cart-subscribe.js
src/components/api/subscribe.js
src/pages/MypageBuyer/SubscribeManage.jsx
src/pages/productDetail/ProductDetail.jsx
src/pages/productDetail/ProductMainInfo.jsx

ex) #1
구독 주문 요청 api 작성
productDetail에 구독 관련 상태 및 로직 추가
(구독 여부(purchaseType), 배송 주기(deliveryCycle), 기간(deliveryPeriodInMonths) 등 상태 추가)
구독 주문 완료 후 마이페이지 이동 처리

feat : 구독 기능 개발

---

src/components/Ui/Popup/Popup.jsx
src/pages/MypageBuyer/BuyerMemberEdit.jsx
src/pages/cart/CartGroupBuy.jsx
src/pages/cart/CartSubscribe.jsx

#82 
일반, 구독, 공동구매 장바구니 관련 팝업 수정
구독 장바구니 팝업 수정

🐛Fix/GroupBuyCartPopup#82

---

src/pages/MypageBuyer/SubscribeManage.css

구독 - 마이페이지 - "적용하기" 버튼 수정했습니다.

Fix : 구독 버튼 수정
